services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 5173:80
    volumes:
      - ./front/html:/usr/share/nginx/html/
      - ./front/css:/usr/share/nginx/html/css/
      - ./front/js:/usr/share/nginx/html/js/
      - ./.logs/nginx:/var/log/nginx